<div class="space-y-5">
    <div class="data-list-heading"><div><h1 class="text-xl font-semibold">Danh mục sản phẩm</h1><p class="mt-1 text-sm text-slate-500">Chuẩn hóa SKU, giá chuẩn và VAT để dùng trong cơ hội/báo giá.</p></div>@can('create', \App\Models\Product::class)<flux:button variant="primary" wire:click="openCreate">Thêm sản phẩm</flux:button>@endcan</div>
    @if(session('success'))<flux:callout variant="success">{{ session('success') }}</flux:callout>@endif
    <div class="crm-card"><div class="mb-4 max-w-sm"><flux:input wire:model.live.debounce.300ms="search" label="Tìm kiếm" placeholder="Tên hoặc SKU" icon="magnifying-glass" /></div>
        <div class="overflow-x-auto"><flux:table><flux:table.columns><flux:table.column>Sản phẩm</flux:table.column><flux:table.column>Đơn vị</flux:table.column><flux:table.column align="end">Giá chuẩn</flux:table.column><flux:table.column>VAT</flux:table.column><flux:table.column>Trạng thái</flux:table.column><flux:table.column /></flux:table.columns><flux:table.rows>
        @forelse($products as $product)<flux:table.row :key="$product->id"><flux:table.cell variant="strong"><div>{{ $product->name }}</div><div class="text-xs font-normal text-slate-500">{{ $product->sku }}</div></flux:table.cell><flux:table.cell>{{ $product->unit }}</flux:table.cell><flux:table.cell align="end">{{ number_format((float)$product->standard_price, 0, ',', '.') }} ₫</flux:table.cell><flux:table.cell>{{ $product->vat_percent }}%</flux:table.cell><flux:table.cell><flux:badge :color="$product->is_active ? 'emerald' : 'zinc'">{{ $product->is_active ? 'Đang dùng' : 'Ngừng dùng' }}</flux:badge></flux:table.cell><flux:table.cell>@can('update',$product)<flux:button size="sm" variant="ghost" wire:click="openEdit({{ $product->id }})">Sửa</flux:button>@endcan</flux:table.cell></flux:table.row>@empty<flux:table.row><flux:table.cell colspan="6" class="py-10 text-center text-slate-500">Chưa có sản phẩm.</flux:table.cell></flux:table.row>@endforelse
        </flux:table.rows></flux:table></div><div class="mt-4">{{ $products->links() }}</div></div>
    <flux:modal wire:model="showEditor" class="w-full max-w-xl"><form wire:submit="save" class="space-y-4"><flux:heading>{{ $editingId ? 'Chỉnh sửa sản phẩm' : 'Thêm sản phẩm' }}</flux:heading><div class="grid gap-4 sm:grid-cols-2"><flux:input wire:model="sku" label="SKU" required /><flux:input wire:model="name" label="Tên sản phẩm/dịch vụ" required /><flux:input wire:model="unit" label="Đơn vị tính" required /><x-forms.money-input model="standardPrice" label="Giá chuẩn" required /><flux:input wire:model="vatPercent" type="number" min="0" max="100" label="VAT (%)" required /></div><flux:textarea wire:model="description" label="Mô tả" /><flux:checkbox wire:model="isActive" label="Đang sử dụng" /><div class="flex justify-end gap-2"><flux:button type="button" variant="ghost" wire:click="$set('showEditor',false)">Hủy</flux:button><flux:button type="submit" variant="primary">Lưu sản phẩm</flux:button></div></form></flux:modal>
</div>
